### ISSUE TITLE
XSD to manifest

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#160]
Add new manifest backend for XSD schemas.

For this task we need to support only reading XSD schema, but we do not need to support writing XSD schemas.

### Testing

Test XSD backend on [RC Broker](https://ws.registrucentras.lt/broker/info.php) XSD schemas.

Following commands should work with all RC Broker XSD schemas:

- Convert XSD to DSA using `spinta copy` command:

      spinta copy -o dsa.csv https://ws.registrucentras.lt/broker/info.php?t=17&f=out

  Ši komanda turėtu nuskaityti XSD failą nurodytą poziciniame argumente ir išsaugoti XSD schemą DSA/CSV formatu. Išsaugant `dsa.csv` turėtu būti užpildyti šie laukai:
  - `dataset` - panaudojant URI, iš pavyzdžio turėtu būti `broker/info_php`
  - `dataset.source` - XSD URL
  - `model` - konvertuotas XSD complex type arba sequence XPath, į DSA kodinį pavadinimą, pavyzdžiui `Dokumentai`.
  - `model.ref` - iš XSD specifikacijos [3.11 Identity-constraint Definitions](https://www.w3.org/TR/xmlschema11-1/#cIdentity-constraint_Definitions).
  - `model.source` - complex type ar sequence XPath iš XSD, pavyzdžiui `//DOKUMENTAI`.
  - `model.description` - iš XSD specifikacijos [3.15 Annotations](https://www.w3.org/TR/xmlschema11-1/#Annotation_details).
  - `property` - konvertuotas XSD elemento arba atributo XPath, į DSA kodinį pavadinimą, pavyzdžiui `doc_id`.
  - `property.type` - convert XSD types to DSA types, see [W3C XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes](https://www.w3.org/TR/xmlschema11-2/).
    - Add `required` constraint if `minOccurs > 0`, byDefault `minOccurs=1`.
    - Add `unique` constraint (don't know if XSD supports that).
  - `property.ref` - iš XSD specifikacijos [3.11 Identity-constraint Definitions](https://www.w3.org/TR/xmlschema11-1/#cIdentity-constraint_Definitions).
  - `property.source` - elemento arba atributo XPath reliatyvus `model.source` XPath, pavyzdžiui `@DOC_ID`.
  - `properyt.description` - iš XSD specifikacijos [3.15 Annotations](https://www.w3.org/TR/xmlschema11-1/#Annotation_details).
  - `enum` - see [4.3.5 enumeration](https://www.w3.org/TR/xmlschema11-2/#rf-enumeration)
  - `enum.source` - enumeration value
  - `enum.description` - anotation

### Resources

- [W3C XML Schema Definition Language (XSD) 1.1 Part 1: Structures](https://www.w3.org/TR/xmlschema11-1/)
- [W3C XML Schema Definition Language (XSD) 1.1 Part 2: Datatypes](https://www.w3.org/TR/xmlschema11-2/)
- [XML Path Language (XPath) 2.0 (Second Edition)](https://www.w3.org/TR/xpath20/)
- [Adding new manifest type](https://spinta.readthedocs.io/en/latest/contrib/manifests.html#adding-new-manifest-type)

### Tasks

- [x] support for XSD `choice` that are in references ([example](https://ws.registrucentras.lt/broker/info.php?t=730&f=out))
- [x] support for references that are inside `choice` ([example](https://ws.registrucentras.lt/broker/info.php?t=40&f=out))
- [x] when there is a property with type `backref`, and a corresponding property with a type `ref` on another model, the `ref` type property is marked as unique. This shouldn't be needed. ([example](https://ws.registrucentras.lt/broker/info.php?t=740&f=out).
- [x] in some cases, an empty model is being created. It should be instead a property on another model. It's being created when one of the `choice` item has only one other item inside of it. ([example](https://ws.registrucentras.lt/broker/info.php?t=5501&f=out)
- [x] circular type declaration. There are cases, when one complexType has an element of another complexType, which has an element of the former complexType. Thus, a circular type reference is being created. ([example](view-source:https://ws.registrucentras.lt/broker/info.php?t=5550&f=out))
- [x]  `complexContent`. `complexContent` type nodes are not covered yet. ([example](view-source:https://ws.registrucentras.lt/broker/info.php?t=1687&f=out))
- [x] choice inside another choice hasn't been covered yet.
- [x] `gYearMonth` type has to be mapped to `date` type and has to have `M` in the `ref` column.
- [x] base64binary conversion to binary using prepare
- [ ] #600
- [x] #601 
- [ ] #603 
- [x] #602 
- [x] #604 
- [x] #605 
- [ ] #613

**Comment by sirex** [comment]
Example:

```xml
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ADMINISTRACINIAI">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ADMINISTRACINIS" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="ADM_KODAS"/>
              <xs:element type="xs:long" name="ADM_ID"/>
              <xs:element type="xs:string" name="TIPAS"/>
              <xs:element type="xs:string" name="TIPO_SANTRUMPA"/>
              <xs:element type="xs:string" name="VARDAS_K"/>
              <xs:element type="xs:string" name="VARDAS_K_LOT"/>
              <xs:element type="xs:long" name="PRIKLAUSO_KODAS"/>
              <xs:element type="xs:long" name="GYV_KODAS"/>
              <xs:element type="xs:date" name="NUO"/>
              <xs:element type="xs:date" name="IKI"/>
              <xs:element type="xs:date" name="ADM_NUO"/>
              <xs:element type="xs:date" name="ADM_IKI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GYVENVIETES">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GYVENVIETE" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="GYV_KODAS"/>
              <xs:element type="xs:long" name="GYV_ID"/>
              <xs:element type="xs:string" name="TIPAS"/>
              <xs:element type="xs:string" name="TIPO_SANTRUMPA"/>
              <xs:element type="xs:string" name="VARDAS_V"/>
              <xs:element type="xs:string" name="VARDAS_V_LOT"/>
              <xs:element type="xs:string" name="VARDAS_K"/>
              <xs:element type="xs:string" name="VARDAS_K_LOT"/>
              <xs:element type="xs:long" name="ADM_KODAS"/>
              <xs:element type="xs:date" name="NUO"/>
              <xs:element type="xs:date" name="IKI"/>
              <xs:element type="xs:date" name="GYV_NUO"/>
              <xs:element type="xs:date" name="GYV_IKI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GATVES">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GATVE" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="GAT_KODAS"/>
              <xs:element type="xs:long" name="GAT_ID"/>
              <xs:element type="xs:string" name="TIPAS"/>
              <xs:element type="xs:string" name="TIPO_SANTRUMPA"/>
              <xs:element type="xs:string" name="VARDAS_K"/>
              <xs:element type="xs:string" name="VARDAS_K_LOT"/>
              <xs:element type="xs:long" name="GYV_KODAS"/>
              <xs:element type="xs:date" name="NUO"/>
              <xs:element type="xs:date" name="IKI"/>
              <xs:element type="xs:date" name="GAT_NUO"/>
              <xs:element type="xs:date" name="GAT_IKI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ADRESAI">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ADRESAS" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="AOB_KODAS"/>
              <xs:element type="xs:long" name="AOB_ID"/>
              <xs:element type="xs:long" name="GYV_KODAS"/>
              <xs:element type="xs:long" name="GAT_KODAS"/>
              <xs:element type="xs:string" name="NR"/>
              <xs:element type="xs:string" name="KORPUSO_NR"/>
              <xs:element type="xs:string" name="PASTO_KODAS"/>
              <xs:element type="xs:date" name="NUO"/>
              <xs:element type="xs:date" name="IKI"/>
              <xs:element type="xs:date" name="AOB_NUO"/>
              <xs:element type="xs:date" name="AOB_IKI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PATALPOS">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PATALPA" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:long" name="PAT_KODAS"/>
              <xs:element type="xs:long" name="PAT_ID"/>
              <xs:element type="xs:long" name="AOB_KODAS"/>
              <xs:element type="xs:string" name="PATALPOS_NR"/>
              <xs:element type="xs:date" name="NUO"/>
              <xs:element type="xs:date" name="IKI"/>
              <xs:element type="xs:date" name="PAT_NUO"/>
              <xs:element type="xs:date" name="PAT_IKI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="KODAI">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="KODAS" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="PASTO_KODAS"/>
              <xs:element type="xs:string" name="PASTO_VIET_PAV"/>
              <xs:element type="xs:date" name="NUO"/>
              <xs:element type="xs:date" name="IKI"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

Converts to DSA:

```
d | r | b | m | property        | type    | ref | source                            | prepare | level | access | uri | title | description
dataset1                        |         |     |                                   |         |       |        |     |       |
  | resource1                   | xml     |     |                                   |         |       |        |     |       |
  |   |   | Administracinis     |         |     | /ADMINISTRACINIAI/ADMINISTRACINIS |         |       |        |     |       |
  |   |   |   | adm_kodas       | integer |     | ADM_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | adm_id          | integer |     | ADM_ID/text()                     |         |       |        |     |       |
  |   |   |   | tipas           | string  |     | TIPAS/text()                      |         |       |        |     |       |
  |   |   |   | tipo_santrumpa  | string  |     | TIPO_SANTRUMPA/text()             |         |       |        |     |       |
  |   |   |   | vardas_k        | string  |     | VARDAS_K/text()                   |         |       |        |     |       |
  |   |   |   | vardas_k_lot    | string  |     | VARDAS_K_LOT/text()               |         |       |        |     |       |
  |   |   |   | priklauso_kodas | integer |     | PRIKLAUSO_KODAS/text()            |         |       |        |     |       |
  |   |   |   | gyv_kodas       | integer |     | GYV_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | nuo             | date    |     | NUO/text()                        |         |       |        |     |       |
  |   |   |   | iki             | date    |     | IKI/text()                        |         |       |        |     |       |
  |   |   |   | adm_nuo         | date    |     | ADM_NUO/text()                    |         |       |        |     |       |
  |   |   |   | adm_iki         | date    |     | ADM_IKI/text()                    |         |       |        |     |       |
                                |         |     |                                   |         |       |        |     |       |
  |   |   | Gyvenviete          |         |     | /GYVENVIETES/GYVENVIETE           |         |       |        |     |       |
  |   |   |   | gyv_kodas       | integer |     | GYV_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | gyv_id          | integer |     | GYV_ID/text()                     |         |       |        |     |       |
  |   |   |   | tipas           | string  |     | TIPAS/text()                      |         |       |        |     |       |
  |   |   |   | tipo_santrumpa  | string  |     | TIPO_SANTRUMPA/text()             |         |       |        |     |       |
  |   |   |   | vardas_v        | string  |     | VARDAS_V/text()                   |         |       |        |     |       |
  |   |   |   | vardas_v_lot    | string  |     | VARDAS_V_LOT/text()               |         |       |        |     |       |
  |   |   |   | vardas_k        | string  |     | VARDAS_K/text()                   |         |       |        |     |       |
  |   |   |   | vardas_k_lot    | string  |     | VARDAS_K_LOT/text()               |         |       |        |     |       |
  |   |   |   | adm_kodas       | integer |     | ADM_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | nuo             | date    |     | NUO/text()                        |         |       |        |     |       |
  |   |   |   | iki             | date    |     | IKI/text()                        |         |       |        |     |       |
  |   |   |   | gyv_nuo         | date    |     | GYV_NUO/text()                    |         |       |        |     |       |
  |   |   |   | gyv_iki         | date    |     | GYV_IKI/text()                    |         |       |        |     |       |
                                |         |     |                                   |         |       |        |     |       |
  |   |   | Gatve               |         |     | /GATVES/GATVE                     |         |       |        |     |       |
  |   |   |   | gat_kodas       | integer |     | GAT_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | gat_id          | integer |     | GAT_ID/text()                     |         |       |        |     |       |
  |   |   |   | tipas           | string  |     | TIPAS/text()                      |         |       |        |     |       |
  |   |   |   | tipo_santrumpa  | string  |     | TIPO_SANTRUMPA/text()             |         |       |        |     |       |
  |   |   |   | vardas_k        | string  |     | VARDAS_K/text()                   |         |       |        |     |       |
  |   |   |   | vardas_k_lot    | string  |     | VARDAS_K_LOT/text()               |         |       |        |     |       |
  |   |   |   | gyv_kodas       | integer |     | GYV_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | nuo             | date    |     | NUO/text()                        |         |       |        |     |       |
  |   |   |   | iki             | date    |     | IKI/text()                        |         |       |        |     |       |
  |   |   |   | gat_nuo         | date    |     | GAT_NUO/text()                    |         |       |        |     |       |
  |   |   |   | gat_iki         | date    |     | GAT_IKI/text()                    |         |       |        |     |       |
                                |         |     |                                   |         |       |        |     |       |
  |   |   | Adresas             |         |     | /ADRESAI/ADRESAS                  |         |       |        |     |       |
  |   |   |   | aob_kodas       | integer |     | AOB_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | aob_id          | integer |     | AOB_ID/text()                     |         |       |        |     |       |
  |   |   |   | gyv_kodas       | integer |     | GYV_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | gat_kodas       | integer |     | GAT_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | nr              | string  |     | NR/text()                         |         |       |        |     |       |
  |   |   |   | korpuso_nr      | string  |     | KORPUSO_NR/text()                 |         |       |        |     |       |
  |   |   |   | pasto_kodas     | string  |     | PASTO_KODAS/text()                |         |       |        |     |       |
  |   |   |   | nuo             | date    |     | NUO/text()                        |         |       |        |     |       |
  |   |   |   | iki             | date    |     | IKI/text()                        |         |       |        |     |       |
  |   |   |   | aob_nuo         | date    |     | AOB_NUO/text()                    |         |       |        |     |       |
  |   |   |   | aob_iki         | date    |     | AOB_IKI/text()                    |         |       |        |     |       |
                                |         |     |                                   |         |       |        |     |       |
  |   |   | Patalpa             |         |     | /PATALPOS/PATALPA                 |         |       |        |     |       |
  |   |   |   | pat_kodas       | integer |     | PAT_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | pat_id          | integer |     | PAT_ID/text()                     |         |       |        |     |       |
  |   |   |   | aob_kodas       | integer |     | AOB_KODAS/text()                  |         |       |        |     |       |
  |   |   |   | patalpos_nr     | string  |     | PATALPOS_NR/text()                |         |       |        |     |       |
  |   |   |   | nuo             | date    |     | NUO/text()                        |         |       |        |     |       |
  |   |   |   | iki             | date    |     | IKI/text()                        |         |       |        |     |       |
  |   |   |   | pat_nuo         | date    |     | PAT_NUO/text()                    |         |       |        |     |       |
  |   |   |   | pat_iki         | date    |     | PAT_IKI/text()                    |         |       |        |     |       |
                                |         |     |                                   |         |       |        |     |       |
  |   |   | Kodas               |         |     | /KODAI/KODAS                      |         |       |        |     |       |
  |   |   |   | pasto_kodas     | string  |     | PASTO_KODAS/text()                |         |       |        |     |       |
  |   |   |   | pasto_viet_pav  | string  |     | PASTO_VIET_PAV/text()             |         |       |        |     |       |
  |   |   |   | nuo             | date    |     | NUO/text()                        |         |       |        |     |       |
  |   |   |   | iki             | date    |     | IKI/text()                        |         |       |        |     |       |
```
