### ISSUE TITLE
Add support for XML files

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#217]
Implement reading data from XML files using [lxml iterparse](https://lxml.de/parsing.html#iterparse-and-iterwalk) functionality, on top of [dask.bag](https://docs.dask.org/en/stable/bag-creation.html) and eventually convert it to [dask.DataFrame](https://docs.dask.org/en/stable/dataframe.html) and do all the filtering and transformations on top of [dask.DataFrame](https://docs.dask.org/en/stable/dataframe.html).

When reading XML with [iterparse](https://lxml.de/parsing.html#iterparse-and-iterwalk), on `end` event, you should get whole element in memory and use xpath expressions from `property.source` to extract property values. xpath expressions are relative to element, specified in `model.source`. `model.source` is also an xpath expression, specifying sequence of elements as objects for the model.

The idea here, is to not load whole XML file into memory, but read it element by element.

When parsing XML, [namespaces specified in manifest file](https://atviriduomenys.readthedocs.io/dsa/dimensijos.html#isoriniu-zodynu-prefiksai), should also be [used in XML parsing](https://lxml.de/tutorial.html#namespaces). So that in XPath, you can use element names with namespace prefixes specified in manifest file.

When loading data from multiple xml files, use `dask.bag.from_sequence(['file1.xml', 'file2.xml', ...]).map(load_from_file).to_dataframe()`.

See: https://atviriduomenys.readthedocs.io/dsa/resource.html#xml

### Tasks

- [x] Basic XML support
- [ ] Fix date issue
- [ ] Add support for parameterization

### Related

- https://github.com/atviriduomenys/spinta/issues/89

### Resources

- [lxml iterparse](https://lxml.de/parsing.html#iterparse-and-iterwalk)
- [Generate RDF from XML](https://rml.io/docs/rml/tutorials/xml/)

**Comment by sirex** [comment]
Grąžinu atgal į Todo, dėl parametrizacijos palaikymo.

**Comment by sirex** [comment]
Bellow you will find a description on how to implement parametrization.

For example, if we have two resource, on is a JSON API, available at
`/pages.json` URL, which returns following data:

```json
{
    "articles": [
        {"id": 1},
        {"id": 2},
    ],
    "next": "/pages.json?page=2"
}
```
On each page, we get list of articles in that page and a link to the next page.

Another resource is an XML file, that returns data about single article, by id:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<article id="1">
    <title>Article 1</title>
</article>
```

For data above, we have a manifest table, that looks like this:


```
d | r | b | m | property | type    | ref  | source            | prepare
ds1                      |         |      |                   |
  | res1                 | json    |      | {url}             |
                         | param   | url  | /pages.json       |
                         |         |      | Page              | loop().select().link
                         |         |      |                   |
  |   |   | Article      |         | id   | .                 |
  |   |   |   | id       | integer |      | more              |
  |   |   | Page         |         | link | .                 |
  |   |   |   | link     | url     |      | more              |
                         |         |      |                   |
ds2                      |         |      |                   |
  | res2                 | xml     |      | /article/{id}.xml |
                         | param   | id   | /ds1/Article      | select().id
                         |         |      |                   |
  |   |   | Article      | id      |      | /article          |
  |   |   |   | id       | integer |      | @id               |
  |   |   |   | title@en | string  |      | title             |
```

Now, if we run this manifest file, we should be able to get data like this:

    get /ds2/Article

```json
{
    "_data": [
        {"id": 1, "title": {"en": "Article 1"}},
        {"id": 2, "title": {"en": "Article 2"}},
        {"id": 3, "title": {"en": "Article 3"}},
        ...
    ]
}
```

Below I will describe, how this should work.


### Parameter value generators

One parameter can be composed of one or multiple value generators, for example:

```
type    | ref  | source      | prepare
param   | url  | /pages.json |
        |      | Page        | select().link
```

Here we have a single parameter named `url`. Name is given in `ref` column or
more precisely in `param.ref` column.

`url` parameter has two value generatros:

1. First generates a single constant value `/pages.json`.

2. Second does `select("Page")` call to retrieve data from `Page` model and
   takse `link` attribute as value for `url` parameter.

For example if `Page` has following data:

```json
{
    "_data": [
        {"link": "/pages.json?page=1"},
        {"link": "/pages.json?page=2"},
        {"link": "/pages.json?page=3"}
    ]
}
```

Then in total, combining all `url` parameter generators, we will get following
values:

- `/pages.json` - a constant value from the first generator
- `/pages.json?page=1` - a first value from the second generator
- `/pages.json?page=2`
- `/pages.json?page=3`



### Multiple parameters

There can be multiple parameters defined, for example:

```
type    | ref | source | prepare
param   | a   | A      | select().value
        | b   | B      | select().value
```

In souch case, we need to produce values liek this:

```python
params = {}
for row1 in select("A"):
    params['a'] = row1.value
    for row2 in select("B")
        params['b'] = row2.value
        # ... proceed by using parameter values
```

First we need to collect all parameter values and then proceed with the data
extraction from the source which requires parameters.


### loop() function

There can be cases, when we don't see all the pages with one request, we only
see the next page, in such cases, we can use `loop()` call, for example:

```
type    | ref  | source      | prepare
param   | url  | /pages.json |
        |      | Page        | loop().select().link
```

Here `loop()` call does multiple `select()` calls until `select()` returns no
data.


### Circular parameter dependencies

When resource have a parameter, that also uses the resource, we have a circular
dependency between parameter and resource, for example:

```
d | r | b | m | property | type    | ref  | source            | prepare
ds1                      |         |      |                   |
  | res1                 | json    |      | {url}             |
                         | param   | url  | /pages.json       |
                         |         |      | Page              | select().link
  |   |   | Page         |         | link | arcticles[]       |
  |   |   |   | link     | url     |      | more              |
```

Here `res1` depends on parameter `url`, but `url` also depends on `res1`,
because second generator of `url` takes values from `Page` model under `res1`
resource.

In souch cases we need to use a cache in form of a stack for `Page` data, to
avoid circular dependency issue.

In the example above, we would do following steps to get `Page` data:

1. First we get first value from `url` parameter, which is a `/pages.json`
   constant.

2. Then we put `url` into `res1.soruce` to get full url for the `res1`.

3. Then we get JSON data from generated URL and select `arcticles[]` array from
   JSON data.

4. At `load` time, we detect, that `url` uses `Page` and this is a circular
   dependency, which need data caching. Using this information collected at
   `load` time, after `Page` data is read, we push just read `Page` data to a
   stack used for parameters with circular dependencies. In this case `Page`
   data would be pushed to a stack of `url` parameter's second generator.

5. Then we emit `Page` data and proceed to next `url` parameter value.

6. Then next `url` parameter value will be read from the stack, not from the
   `Page` model directly. The next value will be `/pages.json?page=1`.

7. Then we put `/pages.json?page=1` value into `res1.source` to get full url.

8. Then we continue from step 3, until we get an emply stack.

The parameter generator stack could be stored in memory.

In this case, if we would have only one generator, then `Page` would return an
empty list, because we start with an empty stack and would not be able to get
any data.

If parameter does not have a circular dependency, then we would not use a
cache, and would call resource directly, to get data stream and using this data
stream, we would produce parameter values.


### Other ways how parameters can be used

There is no need to implement this as part of this task, but just for
information, on how parameters will be used in other places.

1. We can access parameters from `prepare` using `param(name)` function, where
   `name` is parameter name.

2. Using `param(name)` function, we can create model properties, that would get
   value from property.

3. Parameters can also be passed via request, for example `/ds2/Article?id=5`,
   in this case, value generation for `id` parameter will be turned off and a
   passed value is used instead.


### Nots on implementation

I would split this into following tasks:

- Implement a separate function, that would generate `params` dict with all the
  values, of all the parameters. Currently there is a stub function called
  `spinta.datasets.utils.iterparams` which should be implemented, to produce
  generation of all parameter values.

  Take into account, that one parameter, can have multiple generators, and the
  kind of generator is specified in `prepare` column as function. Current we
  need to support constants, `loop()` and `select()` functions for generating
  parameter values.

  There are two types of `select()` one that reads data directly and one with
  circular dependency, that reads data from a cache stack.

- Implement detection of circular dependencies at `load` time and push model
  values to parameter generator stack on model read, if parameter have a
  circular dependency with that model.

- Finally connect everything together.
