### ISSUE TITLE
Saugyklos greitaveikos ir infrastruktūros priemonių  tobulinimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#244]
### Tasks

- [x] #171 
- [ ] https://github.com/atviriduomenys/spinta/issues/359
- [ ] https://github.com/atviriduomenys/spinta/issues/78
- [x] https://github.com/atviriduomenys/spinta/issues/372
- [x] https://github.com/atviriduomenys/spinta/issues/113
- [x] https://github.com/atviriduomenys/spinta/issues/479
