### ISSUE TITLE
Add JSON backend

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/spinta#256]
JSON backend should use Pandas [json_normalize](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.json_normalize.html) function, to normalize data on top of [dask.bag](https://docs.dask.org/en/stable/bag-creation.html). Flattened JSON data should be converted [to dataframe](https://docs.dask.org/en/stable/bag-creation.html#to-dataframes) and all filtering and transformation should be done on top of [dask.DataFrame](https://docs.dask.org/en/stable/dataframe.html).

`model.source` should specify `record_path`, which is split into list by `.`.

`property.source` should specify `meta`. If `property.source` starts with `.`, then it is a `meta` but in a relative to `record_path` form. For example if `record_path` is `["a", "b", "c"]`, then when `property.source` is `.x`, it should be expanded to `["a", "b", "x"]`. For `..x`, `meta` should be `["a", "x"]`.

When loading data from multiple xml files, use `dask.bag.from_sequence(['file1.json', 'file2.json', ...]).map(load_from_file).to_dataframe()`.

###  Tasks

- [x] Add basic support for JSON
- [ ]  Fix date issue https://github.com/atviriduomenys/spinta/pull/456#discussion_r1289565710
- [ ] Add parametrization support

### See also

- https://towardsdatascience.com/all-pandas-json-normalize-you-should-know-for-flattening-json-13eae1dfb7dd
- https://itsmycode.com/python-jsonpath/
- https://rml.io/docs/rml/tutorials/json/

### Related

- #98

**Comment by sirex** [comment]
Grąžinu dėl parametrizacijos.
