### ISSUE TITLE
Ištestuoti likusias versijos SPINTA 0.1.65 užduotis

### ISSUE THREAD

**Issue by ATEAanalyst** [atviriduomenys/spinta#655]
## 0.1.65 versijos užduotys

Testuojamų užduočių sąrašas

- [x] Testuoti `push` komandą su dideliu kiekiu duomenų.
- [ ] Testuoti `push` komandą kai atsiranda tinklo klaidos.
- [ ] Testuoti `push` komandą kai nepalaikom puslapiavimo.

## Testavimo aplinkoje:

- [x] https://github.com/atviriduomenys/spinta/issues/476 -- `connect(schema: ...)` gali neveikti, reikia pasigilinti daugiau
- [x] https://github.com/atviriduomenys/spinta/issues/96 -- Reikia patikslinti, kas turi veikti ir ką reikia daryti su trūkstamom dalim
- [x] https://github.com/atviriduomenys/spinta/issues/346
- [x] https://github.com/atviriduomenys/spinta/issues/391
- [x] https://github.com/atviriduomenys/spinta/issues/161 -- Reikia patikslinti ką daryti su trūkstamom dalim
- [x] https://github.com/atviriduomenys/spinta/issues/397
- [x] https://github.com/atviriduomenys/spinta/issues/122
- [x] https://github.com/atviriduomenys/spinta/issues/204
- [x] https://github.com/atviriduomenys/spinta/issues/458
- [ ] https://github.com/atviriduomenys/spinta/issues/113
- [ ] https://github.com/atviriduomenys/spinta/issues/379 -- multi nested gali būti nepalaikomas
- [x] https://github.com/atviriduomenys/spinta/issues/380
- [x] https://github.com/atviriduomenys/spinta/issues/437
- [ ] https://github.com/atviriduomenys/spinta/issues/372
- [ ] https://github.com/atviriduomenys/spinta/issues/477
- [ ] https://github.com/atviriduomenys/spinta/issues/479
- [x] https://github.com/atviriduomenys/spinta/issues/217 -- nepavyksta atkartoti date bugo, gali būti jog array tipas blogai sukuriamas
- [x] https://github.com/atviriduomenys/spinta/issues/256 -- nepavyksta atkartoti date bugo, gali būti jog array tipas blogai sukuriamas
- [ ] https://github.com/atviriduomenys/spinta/issues/580
